config/routes.rb
Rails.application.routes.draw do
  resources :shows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/shows" => "shows#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/show.rb
include HTTParty

class Show < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = HTTParty.get('http://api.tvmaze.com/shows')
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:name, :type, :language, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvShows</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :show_name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :show_type %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :show_language %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :show_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Language</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show['name'] %></td>
        <td><%= show['type'] %></td>
        <td><%= show['language'] %></td>
        <td><%= show['status'] %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @show.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @show.type %>
</p>

<p>
  <strong>Language:</strong>
  <%= @show.language %>
</p>

<p>
  <strong>Status:</strong>
  <%= @show.status %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>